#!/usr/bin/env python3
"""Generate the demo transport payload: a recognizable recon image (sonde-imh.1).

The ARDOP demo sends this image across real ARDOP frames; the frontend rebuilds it
from what decoded. It must be unmistakably recognizable so a clean transfer clearly
"arrives" and a lossy one clearly degrades. We synthesize a dusk scene with an
antenna tower — on-theme (HF radio), deterministic, offline, and JPEG-friendly
(smooth gradients compress small). Writes:

  demo/site/assets/payload.bin          the JPEG bytes (the whole payload is the image)
  demo/site/assets/payload.offsets.json single "image" field [0, len]
  demo/site/assets/source-credit.txt    credit line

Run:  python3 demo/ardop/make_payload.py
Requires Pillow. Re-runnable; deterministic.
"""
import io
import json
import os

from PIL import Image, ImageDraw

W, H = 256, 192
OUT = os.path.join(os.path.dirname(__file__), "../site/assets")


def _lerp(a, b, t):
    return tuple(int(a[i] + (b[i] - a[i]) * t) for i in range(3))


def render():
    im = Image.new("RGB", (W, H))
    px = im.load()
    sky_top = (24, 26, 64)      # deep indigo
    sky_horizon = (250, 150, 70)  # warm dusk
    horizon_y = int(H * 0.66)
    # Sky gradient.
    for y in range(horizon_y):
        t = (y / horizon_y) ** 1.6
        col = _lerp(sky_top, sky_horizon, t)
        for x in range(W):
            px[x, y] = col
    d = ImageDraw.Draw(im)
    # Sun near the horizon.
    sx, sy, sr = int(W * 0.30), int(horizon_y * 0.82), 22
    for r in range(sr, 0, -1):
        t = r / sr
        d.ellipse([sx - r, sy - r, sx + r, sy + r], fill=_lerp((255, 240, 200), sky_horizon, t))
    # Distant ridge + ground.
    d.polygon([(0, horizon_y), (W * 0.25, horizon_y - 26), (W * 0.5, horizon_y - 6),
               (W * 0.78, horizon_y - 30), (W, horizon_y - 10), (W, H), (0, H)],
              fill=(40, 36, 52))
    d.rectangle([0, horizon_y + 14, W, H], fill=(20, 18, 28))
    # Antenna tower (lattice triangle) + guy lines, right of centre.
    tx, base_y, top_y = int(W * 0.70), horizon_y + 8, int(H * 0.10)
    half_b, half_t = 16, 3
    tower = (12, 12, 18)
    d.polygon([(tx - half_b, base_y), (tx - half_t, top_y),
               (tx + half_t, top_y), (tx + half_b, base_y)], fill=tower)
    # Cross-bracing rungs.
    rungs = 9
    for i in range(rungs + 1):
        t = i / rungs
        y = base_y + (top_y - base_y) * t
        hw = half_b + (half_t - half_b) * t
        d.line([(tx - hw, y), (tx + hw, y)], fill=tower, width=1)
    for i in range(rungs):
        t0, t1 = i / rungs, (i + 1) / rungs
        y0, y1 = base_y + (top_y - base_y) * t0, base_y + (top_y - base_y) * t1
        hw0 = half_b + (half_t - half_b) * t0
        hw1 = half_b + (half_t - half_b) * t1
        s = -1 if i % 2 else 1
        d.line([(tx - s * hw0, y0), (tx + s * hw1, y1)], fill=tower, width=1)
    # Guy lines + beacon.
    d.line([(tx, top_y + 6), (tx - 52, base_y)], fill=(60, 56, 70), width=1)
    d.line([(tx, top_y + 6), (tx + 52, base_y)], fill=(60, 56, 70), width=1)
    d.line([(tx, top_y), (tx, top_y - 10)], fill=(120, 120, 140), width=1)
    d.ellipse([tx - 3, top_y - 14, tx + 3, top_y - 8], fill=(255, 80, 80))
    return im


def main():
    im = render()
    # Encode JPEG at a quality that keeps it a few KB (a handful of ARDOP frames).
    buf = io.BytesIO()
    im.save(buf, format="JPEG", quality=62, optimize=True)
    data = buf.getvalue()
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "payload.bin"), "wb") as f:
        f.write(data)
    with open(os.path.join(OUT, "payload.offsets.json"), "w") as f:
        json.dump({
            "total_len": len(data),
            "fields": [{"label": "image", "start": 0, "end": len(data)}],
            "image_byte_len": len(data),
        }, f, indent=2)
    with open(os.path.join(OUT, "source-credit.txt"), "w") as f:
        f.write("Recon image: synthetic dusk antenna-tower scene, generated by "
                "demo/ardop/make_payload.py (CC0 / public domain).\n")
    print(f"payload.bin: {len(data)} bytes ({W}x{H} JPEG)")


if __name__ == "__main__":
    main()
